[book]
authors = ["ascheffler"]
language = "en"
multilingual = false
src = "src"
title = "VST3 Developer Portal"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[output.html]
no-section-label = true
default-theme = "steinberg"
preferred-dark-theme = "steinberg"

[output.html.fold]
enable = true
level = 1

[output.html.redirect]
"display/VST/Main+benefits+of+VST+3/index.html" = "../../../pages/Main+benefits+of+VST+3/index.html"
