name: GitHub Pages

on:
  push:
    branches:
      - deploy
  pull_request:

jobs:
  deploy:
    name: Build mdbook
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: jontze/action-mdbook@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          mdbook-version: "~0.3.0"
          mermaid-version: "~0.8.0"
          toc-version: "~0.7.0"
          use-linkcheck: false
          use-mermaid: true
          use-toc: true
          use-opengh: false
      - run: mdbook build

      - name: Deploy
        uses: jontze/action-mdbook@v1
        if: ${{ github.ref == 'refs/heads/deploy' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
 